import { Router } from 'express';
import type { HiveContext } from '../../../../../src/context.js';

export function createChannelRoutes(ctx: HiveContext): Router {
  const router = Router();

  // GET /api/channels — list all channels with message counts
  router.get('/', (_req, res) => {
    try {
      const channelIds = ctx.access.getAccessibleChannels(0); // super-user sees all
      const channels = channelIds.map(channelId => {
        const ch = ctx.channels.getChannel(channelId);
        const members = ctx.channels.getMembers(channelId);
        const memberAliases = members.map(m => {
          try { return ctx.chatAdapter.resolveId(m.personId); } catch { return `person:${m.personId}`; }
        });
        const history = ctx.messages.history(channelId, { limit: 1 });

        return {
          id: channelId,
          name: channelId,
          displayName: ctx.channels.formatForDisplay(channelId, 0),
          members: memberAliases,
          createdAt: ch?.createdAt ?? new Date().toISOString(),
          autoGenerated: false,
          messageCount: history.total,
        };
      });
      res.json(channels);
    } catch (err: any) {
      console.error('[channels] Error:', err.message);
      res.status(500).json({ error: err.message });
    }
  });

  // GET /api/channels/:name/messages
  router.get('/:name/messages', (req, res) => {
    try {
      const channelId = req.params.name;
      const limit = parseInt(req.query.limit as string) || 50;
      const history = ctx.messages.history(channelId, { limit });

      res.json(history.messages.map(m => ({
        id: `${m.channelId}:${m.seq}`,
        channel: m.channelId,
        sender: m.senderAlias,
        content: m.content,
        timestamp: m.timestamp,
      })));
    } catch (err: any) {
      console.error('[channels/messages] Error:', err.message);
      res.status(500).json({ error: err.message });
    }
  });

  return router;
}
