import { Router } from 'express';
import type { HiveContext } from '../../../../../src/context.js';

export function createConversationRoutes(ctx: HiveContext): Router {
  const router = Router();

  // GET /api/conversations — list all conversations with message counts
  router.get('/', (_req, res) => {
    try {
      const conversationIds = ctx.access.getAccessibleConversations(0); // super-user sees all
      const conversations = conversationIds.map(conversationId => {
        const ch = ctx.conversations.getConversation(conversationId);
        const members = ctx.conversations.getMembers(conversationId);
        const memberAliases = members.map(m => {
          try { return ctx.chatAdapter.resolveId(m.personId); } catch { return `person:${m.personId}`; }
        });
        const history = ctx.messages.history(conversationId, { limit: 1 });

        return {
          id: conversationId,
          name: conversationId,
          type: ch?.type ?? (conversationId.startsWith('dm:') ? 'dm' : 'group'),
          displayName: ctx.conversations.formatForDisplay(conversationId, 0),
          members: memberAliases,
          createdAt: ch?.createdAt ?? new Date().toISOString(),
          autoGenerated: false,
          messageCount: history.total,
        };
      });
      res.json(conversations);
    } catch (err: any) {
      console.error('[conversations] Error:', err.message);
      res.status(500).json({ error: err.message });
    }
  });

  // GET /api/conversations/:name/messages
  router.get('/:name/messages', (req, res) => {
    try {
      const conversationId = req.params.name;
      const limit = parseInt(req.query.limit as string) || 50;
      const history = ctx.messages.history(conversationId, { limit });

      res.json({
        messages: history.messages.map(m => ({
          id: `${m.conversationId}:${m.seq}`,
          conversation: m.conversationId,
          sender: m.senderAlias,
          content: m.content,
          timestamp: m.timestamp,
        })),
        total: history.total,
      });
    } catch (err: any) {
      console.error('[conversations/messages] Error:', err.message);
      res.status(500).json({ error: err.message });
    }
  });

  return router;
}
