import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import path from 'path';
import fs from 'fs';
import os from 'os';
import type { AgentConfig, OrgChart } from '../../src/types.js';
import { AgentStateStore } from '../../src/state/agent-state.js';
import { SqliteCommsProvider } from '../../src/comms/sqlite-provider.js';
import { AuditStore } from '../../src/audit/store.js';
import { ChannelManager } from '../../src/comms/channel-manager.js';
import { PidFile } from '../../src/orchestrator/pid-file.js';

// Mock check-work to avoid spawning Claude CLI
vi.mock('../../src/daemon/check-work.js', () => ({
  checkWork: vi.fn(async () => ({
    agentId: 'ceo',
    inboxCount: 0,
    agentInvoked: false,
    recheckImmediately: false,
    durationMs: 10,
  })),
}));

import { Daemon } from '../../src/daemon/daemon.js';
import { checkWork } from '../../src/daemon/check-work.js';

const mockCheckWork = vi.mocked(checkWork);

function makeOrgChart(): OrgChart {
  const ceoConfig: AgentConfig = {
    id: 'ceo',
    identity: { name: 'CEO', role: 'CEO', model: 'sonnet', tools: ['Read'] },
    dir: '/tmp/org/ceo',
    depth: 0,
    parentId: null,
    childIds: [],
    files: { identity: '', soul: '', bureau: '## Direct Channels\n- #board — immediate', priorities: '', routine: '', memory: '', protocols: '' },
  };

  return {
    root: ceoConfig,
    agents: new Map([['ceo', ceoConfig]]),
    channels: [{ name: 'board', autoGenerated: false, memberIds: ['ceo'] }, { name: 'all-hands', autoGenerated: true, memberIds: ['ceo'] }],
  };
}

describe('Daemon', () => {
  let tmpDir: string;
  let stateStore: AgentStateStore;
  let comms: SqliteCommsProvider;
  let audit: AuditStore;

  beforeEach(() => {
    vi.clearAllMocks();
    vi.useFakeTimers();
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'hive-daemon-'));
    stateStore = new AgentStateStore(path.join(tmpDir, 'state.db'));
    comms = new SqliteCommsProvider(path.join(tmpDir, 'comms.db'));
    audit = new AuditStore(path.join(tmpDir, 'audit.db'));
  });

  afterEach(async () => {
    vi.useRealTimers();
    stateStore.close();
    comms.close();
    audit.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  function createDaemon() {
    const orgChart = makeOrgChart();
    const channelManager = new ChannelManager(comms);

    // Mock memory manager
    const memory = {
      indexAll: vi.fn(async () => {}),
      search: vi.fn(async () => []),
      indexAgent: vi.fn(async () => ({ indexed: 0, skipped: 0, chunks: 0 })),
      getStore: vi.fn(),
      close: vi.fn(),
    } as any;

    return new Daemon({
      orgChart,
      comms,
      audit,
      state: stateStore,
      channelManager,
      memory,
      dataDir: tmpDir,
      orgDir: path.join(tmpDir, 'org'),
      pidFilePath: path.join(tmpDir, 'hive.pid'),
      tickIntervalMs: 600_000,
      coalesceMs: 100,
    });
  }

  it('starts, registers agents, and writes PID file', async () => {
    const daemon = createDaemon();
    await daemon.start();

    const pidFile = new PidFile(path.join(tmpDir, 'hive.pid'));
    expect(pidFile.isRunning()).toBe(true);

    await daemon.stop();
  });

  it('prevents duplicate instances', async () => {
    const d1 = createDaemon();
    await d1.start();

    const d2 = createDaemon();
    await expect(d2.start()).rejects.toThrow(/already running/);

    await d1.stop();
  });

  it('schedules periodic ticks that call checkWork', async () => {
    const daemon = createDaemon();
    await daemon.start();

    // Advance past one tick interval
    vi.advanceTimersByTime(600_001);

    // checkWork should have been called at least once
    expect(mockCheckWork).toHaveBeenCalled();

    await daemon.stop();
  });

  it('triggers immediate checkWork on direct channel signal', async () => {
    const daemon = createDaemon();
    await daemon.start();

    // Simulate a message arriving on #board (direct channel for CEO)
    daemon.signalChannel('board');

    // Advance past coalesce window
    vi.advanceTimersByTime(101);

    expect(mockCheckWork).toHaveBeenCalled();

    await daemon.stop();
  });

  it('stops gracefully — drains lanes and removes PID', async () => {
    const daemon = createDaemon();
    await daemon.start();

    await daemon.stop();

    const pidFile = new PidFile(path.join(tmpDir, 'hive.pid'));
    expect(pidFile.isRunning()).toBe(false);
  });
});
