export interface Agent {
  id: string;
  name: string;
  role: string;
  emoji?: string;
  model: string;
  status: string;
  lastHeartbeat?: string;
  lastInvocation?: string;
  currentTask?: string;
}

export interface OrgAgent {
  id: string;
  name: string;
  role: string;
  emoji?: string;
  model: string;
  depth: number;
  parentId: string | null;
  childIds: string[];
}

export interface OrgData {
  root: string;
  agents: OrgAgent[];
  channels: Array<{ name: string; memberIds: string[]; autoGenerated: boolean }>;
}

export interface AgentDetail {
  id: string;
  identity: { name: string; role: string; model: string; emoji?: string; tools: string[] };
  depth: number;
  parentId: string | null;
  childIds: string[];
  dir: string;
  state: { agentId: string; status: string; lastInvocation?: string; lastHeartbeat?: string; currentTask?: string; pid?: number };
  files: { identity: string; soul: string; bureau: string; priorities: string; routine: string; memory: string };
  recentInvocations: Invocation[];
  tokenTotals: { totalIn: number; totalOut: number };
}

export interface Message {
  id: string;
  channel: string;
  sender: string;
  content: string;
  timestamp: string;
  mentions?: string[];
}

export interface Invocation {
  id: string;
  agentId: string;
  invocationType: string;
  model: string;
  tokensIn: number | null;
  tokensOut: number | null;
  cacheReadTokens: number | null;
  cacheCreationTokens: number | null;
  durationMs: number | null;
  inputSummary: string | null;
  outputSummary: string | null;
  actionSummary: string | null;
  channel: string | null;
  timestamp: string;
}

export interface Channel {
  id: string;
  name: string;
  members: string[];
  createdAt: string;
  autoGenerated: boolean;
  messageCount: number;
}

export interface OrgMeta {
  rootAlias: string | null;
  rootName: string;
  boardChannel: string;
}
