import fs from 'fs/promises';
import path from 'path';
import matter from 'gray-matter';
import type { AgentConfig, AgentIdentity, OrgChart, ChannelDef } from '../types.js';

const AGENT_FILES = ['IDENTITY.md', 'SOUL.md', 'BUREAU.md', 'PRIORITIES.md', 'ROUTINE.md', 'MEMORY.md'];
const SKIP_DIRS = ['.claude', '.workspace', '.archive', '.proposals', 'memory', 'node_modules', '.git'];

async function isAgentDir(dir: string): Promise<boolean> {
  try {
    await fs.access(path.join(dir, 'IDENTITY.md'));
    return true;
  } catch {
    return false;
  }
}

function deriveAgentId(agentPath: string, orgRoot: string): string {
  const relative = path.relative(orgRoot, agentPath);
  if (relative === '' || relative === '.') return 'root';
  // org/ceo/engineering/eng-1 → ceo-engineering-eng-1
  // But the first agent folder is typically just "ceo"
  return relative.split(path.sep).filter(s => s !== '').join('-');
}

function deriveChannelName(agentPath: string, orgRoot: string): string | null {
  const relative = path.relative(orgRoot, agentPath);
  const parts = relative.split(path.sep).filter(s => s !== '');
  if (parts.length < 2) return null;
  // Use last two significant segments: "engineering/backend" → "eng-backend"
  const parent = parts[parts.length - 2];
  const team = parts[parts.length - 1];
  return `${parent}-${team}`;
}

export async function readAgentFiles(dir: string): Promise<AgentConfig['files']> {
  const read = async (name: string): Promise<string> => {
    try {
      return await fs.readFile(path.join(dir, name), 'utf-8');
    } catch {
      return '';
    }
  };
  return {
    identity: await read('IDENTITY.md'),
    soul: await read('SOUL.md'),
    bureau: await read('BUREAU.md'),
    priorities: await read('PRIORITIES.md'),
    routine: await read('ROUTINE.md'),
    memory: await read('MEMORY.md'),
  };
}

export function parseIdentityFrontmatter(content: string): AgentIdentity {
  const { data } = matter(content);
  return {
    name: data.name ?? 'Unknown',
    role: data.role ?? 'Unknown',
    model: data.model ?? 'sonnet',
    emoji: data.emoji,
    vibe: data.vibe,
    tools: data.tools ?? ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
  };
}

async function walkIntermediate(
  dir: string,
  orgRoot: string,
  parentDepth: number,
  parentId: string,
  parentConfig: AgentConfig,
  agents: Map<string, AgentConfig>,
): Promise<void> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory() || SKIP_DIRS.includes(entry.name)) continue;
    const childDir = path.join(dir, entry.name);
    if (await isAgentDir(childDir)) {
      const child = await walkAgents(childDir, orgRoot, parentDepth + 1, parentId, agents);
      if (child) parentConfig.childIds.push(child.id);
    } else {
      // Keep recursing through intermediate directories
      await walkIntermediate(childDir, orgRoot, parentDepth, parentId, parentConfig, agents);
    }
  }
}

async function walkAgents(
  dir: string,
  orgRoot: string,
  depth: number,
  parentId: string | null,
  agents: Map<string, AgentConfig>,
): Promise<AgentConfig | null> {
  if (!(await isAgentDir(dir))) return null;

  const id = deriveAgentId(dir, orgRoot);
  const files = await readAgentFiles(dir);
  const identity = parseIdentityFrontmatter(files.identity);

  const config: AgentConfig = {
    id,
    identity,
    dir,
    depth,
    parentId,
    childIds: [],
    files,
  };

  agents.set(id, config);

  // Scan subdirectories for child agents
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory() || SKIP_DIRS.includes(entry.name)) continue;
    const childDir = path.join(dir, entry.name);

    // Check if this dir itself is an agent, or contains agents
    if (await isAgentDir(childDir)) {
      const child = await walkAgents(childDir, orgRoot, depth + 1, id, agents);
      if (child) config.childIds.push(child.id);
    } else {
      // Intermediate directory (e.g., "engineering/") — recurse fully
      await walkIntermediate(childDir, orgRoot, depth, id, config, agents);
    }
  }

  return config;
}

function generateChannels(agents: Map<string, AgentConfig>, orgRoot: string): ChannelDef[] {
  const channels: ChannelDef[] = [
    { name: 'all-hands', autoGenerated: true, memberIds: Array.from(agents.keys()) },
    { name: 'board', autoGenerated: true, memberIds: ['ceo'] },
    { name: 'approvals', autoGenerated: true, memberIds: ['ceo'] },
  ];

  // Leadership channel: CEO + direct reports
  const root = Array.from(agents.values()).find(a => a.depth === 0);
  if (root) {
    channels.push({
      name: 'leadership',
      autoGenerated: true,
      memberIds: [root.id, ...root.childIds],
    });
  }

  // Team channels from folder structure
  for (const agent of agents.values()) {
    if (agent.childIds.length > 0) {
      const channelName = deriveChannelName(agent.dir, orgRoot);
      if (channelName && !channels.find(c => c.name === channelName)) {
        channels.push({
          name: channelName,
          autoGenerated: true,
          memberIds: [agent.id, ...agent.childIds],
        });
      }
    }
  }

  return channels;
}

export async function parseOrgTree(orgRoot: string): Promise<OrgChart> {
  const agents = new Map<string, AgentConfig>();

  // Find the root agent directory (first dir with IDENTITY.md)
  const entries = await fs.readdir(orgRoot, { withFileTypes: true });
  let root: AgentConfig | null = null;

  for (const entry of entries) {
    if (!entry.isDirectory() || SKIP_DIRS.includes(entry.name)) continue;
    const candidateDir = path.join(orgRoot, entry.name);
    root = await walkAgents(candidateDir, orgRoot, 0, null, agents);
    if (root) break;
  }

  if (!root) {
    throw new Error(`No agent found in org root: ${orgRoot}. Expected a directory with IDENTITY.md.`);
  }

  const channels = generateChannels(agents, orgRoot);

  return { root, agents, channels };
}
