export interface AgentIdentity {
  name: string;
  role: string;
  model: string;
  emoji?: string;
  vibe?: string;
  tools: string[];
}

export interface AgentConfig {
  id: string;                    // Derived from folder path: "ceo" or "ceo-engineering-eng-1"
  identity: AgentIdentity;       // Parsed from IDENTITY.md frontmatter
  dir: string;                   // Absolute path to agent folder
  depth: number;                 // 0 = CEO, 1 = VP, etc.
  parentId: string | null;       // Parent agent ID
  childIds: string[];            // Direct report IDs
  files: {
    identity: string;            // Full content of IDENTITY.md
    soul: string;                // Full content of SOUL.md
    bureau: string;              // Full content of BUREAU.md
    priorities: string;          // Full content of PRIORITIES.md
    routine: string;             // Full content of ROUTINE.md
    memory: string;              // Full content of MEMORY.md
  };
}

export interface OrgChart {
  root: AgentConfig;
  agents: Map<string, AgentConfig>;  // id → config
  channels: ChannelDef[];
}

export interface ChannelDef {
  name: string;                  // e.g., "eng-backend"
  autoGenerated: boolean;
  memberIds: string[];
}

export interface AuditEntry {
  id: string;
  agentId: string;
  invocationType: 'triage' | 'main' | 'memory' | 'proposal' | 'comms';
  model: string;
  tokensIn?: number;
  tokensOut?: number;
  durationMs?: number;
  inputSummary?: string;
  outputSummary?: string;
  channel?: string;
  timestamp: Date;
}

export interface AgentState {
  agentId: string;
  status: 'active' | 'idle' | 'working' | 'disposed' | 'errored';
  lastInvocation?: Date;
  lastHeartbeat?: Date;
  currentTask?: string;
  pid?: number;
}

export interface SpawnResult {
  stdout: string;
  stderr: string;
  exitCode: number;
  durationMs: number;
  tokensIn?: number;
  tokensOut?: number;
}

// Re-export comms types for convenience
export type { Message, Channel, ICommsProvider } from './comms/types.js';
