import Database from 'better-sqlite3';
import { randomUUID } from 'crypto';
import type { Message, Channel, ICommsProvider } from './types.js';

function extractMentions(content: string): string[] {
  const matches = content.match(/@([\w-]+)/g);
  return matches ? matches.map(m => m.slice(1)) : [];
}

function rowToMessage(row: any): Message {
  return {
    id: row.id,
    channel: row.channel,
    sender: row.sender,
    content: row.content,
    thread: row.thread ?? undefined,
    mentions: row.mentions ? JSON.parse(row.mentions) : undefined,
    timestamp: new Date(row.timestamp),
    metadata: row.metadata ? JSON.parse(row.metadata) : undefined,
  };
}

function rowToChannel(row: any, members: string[]): Channel {
  return {
    id: row.id,
    name: row.name,
    members,
    createdAt: new Date(row.created_at),
    autoGenerated: row.auto_generated === 1,
  };
}

export class SqliteCommsProvider implements ICommsProvider {
  private db: Database.Database;

  constructor(dbPath: string) {
    this.db = new Database(dbPath);
    this.db.pragma('journal_mode = WAL');
    this.db.pragma('foreign_keys = ON');
    this.migrate();
  }

  private migrate(): void {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS channels (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        auto_generated INTEGER NOT NULL DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      );

      CREATE TABLE IF NOT EXISTS channel_members (
        channel_id TEXT NOT NULL,
        agent_id TEXT NOT NULL,
        joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (channel_id, agent_id),
        FOREIGN KEY (channel_id) REFERENCES channels(id)
      );

      CREATE TABLE IF NOT EXISTS messages (
        seq INTEGER PRIMARY KEY AUTOINCREMENT,
        id TEXT NOT NULL UNIQUE,
        channel TEXT NOT NULL,
        sender TEXT NOT NULL,
        content TEXT NOT NULL,
        thread TEXT,
        mentions TEXT,
        metadata TEXT,
        timestamp DATETIME DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now')),
        FOREIGN KEY (channel) REFERENCES channels(name)
      );
      CREATE INDEX IF NOT EXISTS idx_messages_channel ON messages(channel);
      CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender);
      CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp);
      CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread);

      CREATE TABLE IF NOT EXISTS read_receipts (
        agent_id TEXT NOT NULL,
        message_id TEXT NOT NULL,
        read_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (agent_id, message_id),
        FOREIGN KEY (message_id) REFERENCES messages(id)
      );
    `);

    // FTS5 virtual table for full-text search on message content
    // Wrapped in try-catch because CREATE VIRTUAL TABLE IF NOT EXISTS
    // is not supported in older SQLite versions
    try {
      this.db.exec(`
        CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
          id UNINDEXED,
          channel UNINDEXED,
          sender UNINDEXED,
          content,
          content_rowid='seq'
        );
      `);
    } catch {
      // FTS table already exists
    }

    // Triggers to keep FTS in sync with messages table
    this.db.exec(`
      CREATE TRIGGER IF NOT EXISTS messages_ai AFTER INSERT ON messages BEGIN
        INSERT INTO messages_fts(rowid, id, channel, sender, content)
        VALUES (NEW.seq, NEW.id, NEW.channel, NEW.sender, NEW.content);
      END;

      CREATE TRIGGER IF NOT EXISTS messages_ad AFTER DELETE ON messages BEGIN
        INSERT INTO messages_fts(messages_fts, rowid, id, channel, sender, content)
        VALUES ('delete', OLD.seq, OLD.id, OLD.channel, OLD.sender, OLD.content);
      END;
    `);
  }

  async createChannel(name: string, members?: string[]): Promise<Channel> {
    const existing = this.db.prepare('SELECT id FROM channels WHERE name = ?').get(name);
    if (existing) {
      throw new Error(`Channel already exists: ${name}`);
    }

    const id = randomUUID();
    this.db.prepare(
      'INSERT INTO channels (id, name, auto_generated) VALUES (?, ?, 0)',
    ).run(id, name);

    const memberList = members ?? [];
    const insertMember = this.db.prepare(
      'INSERT INTO channel_members (channel_id, agent_id) VALUES (?, ?)',
    );
    for (const agentId of memberList) {
      insertMember.run(id, agentId);
    }

    return {
      id,
      name,
      members: memberList,
      createdAt: new Date(),
      autoGenerated: false,
    };
  }

  async listChannels(): Promise<Channel[]> {
    const rows = this.db.prepare('SELECT * FROM channels ORDER BY name').all() as any[];
    return rows.map((row) => {
      const memberRows = this.db.prepare(
        'SELECT agent_id FROM channel_members WHERE channel_id = ?',
      ).all(row.id) as any[];
      return rowToChannel(row, memberRows.map((m: any) => m.agent_id));
    });
  }

  async postMessage(
    channel: string,
    sender: string,
    content: string,
    opts?: { thread?: string },
  ): Promise<Message> {
    // Verify channel exists
    const ch = this.db.prepare('SELECT id FROM channels WHERE name = ?').get(channel);
    if (!ch) {
      throw new Error(`Channel not found: ${channel}`);
    }

    const id = randomUUID();
    const thread = opts?.thread ?? null;
    const mentions = extractMentions(content);
    const mentionsJson = mentions.length > 0 ? JSON.stringify(mentions) : null;

    this.db.prepare(
      'INSERT INTO messages (id, channel, sender, content, thread, mentions) VALUES (?, ?, ?, ?, ?, ?)',
    ).run(id, channel, sender, content, thread, mentionsJson);

    // Read back the row to get the actual timestamp
    const row = this.db.prepare('SELECT * FROM messages WHERE id = ?').get(id) as any;
    return rowToMessage(row);
  }

  async readChannel(
    channel: string,
    opts?: { limit?: number; since?: Date },
  ): Promise<Message[]> {
    let sql: string;
    const params: unknown[] = [channel];

    if (opts?.limit && opts.limit > 0) {
      // When limit is specified, get the N most recent, then return in chronological order
      if (opts?.since) {
        sql = `
          SELECT * FROM (
            SELECT * FROM messages WHERE channel = ? AND timestamp > ? ORDER BY seq DESC LIMIT ?
          ) sub ORDER BY seq ASC
        `;
        params.push(opts.since.toISOString(), opts.limit);
      } else {
        sql = `
          SELECT * FROM (
            SELECT * FROM messages WHERE channel = ? ORDER BY seq DESC LIMIT ?
          ) sub ORDER BY seq ASC
        `;
        params.push(opts.limit);
      }
    } else if (opts?.since) {
      sql = 'SELECT * FROM messages WHERE channel = ? AND timestamp > ? ORDER BY seq ASC';
      params.push(opts.since.toISOString());
    } else {
      sql = 'SELECT * FROM messages WHERE channel = ? ORDER BY seq ASC';
    }

    const rows = this.db.prepare(sql).all(...params) as any[];
    return rows.map(rowToMessage);
  }

  async searchHistory(
    query: string,
    opts?: { channel?: string; sender?: string },
  ): Promise<Message[]> {
    // Use FTS5 for full-text search
    // Escape FTS5 special characters and add wildcard
    const ftsQuery = query.replace(/['"*()]/g, '').trim();
    if (!ftsQuery) return [];

    let sql = `
      SELECT m.* FROM messages m
      INNER JOIN messages_fts fts ON m.seq = fts.rowid
      WHERE messages_fts MATCH ?
    `;
    const params: unknown[] = [`"${ftsQuery}"`];

    if (opts?.channel) {
      sql += ' AND m.channel = ?';
      params.push(opts.channel);
    }

    if (opts?.sender) {
      sql += ' AND m.sender = ?';
      params.push(opts.sender);
    }

    sql += ' ORDER BY m.timestamp DESC';

    const rows = this.db.prepare(sql).all(...params) as any[];
    return rows.map(rowToMessage);
  }

  async getUnread(agentId: string): Promise<Message[]> {
    // Get all messages in channels where agentId is a member,
    // excluding messages sent by the agent itself,
    // excluding messages already marked as read
    const sql = `
      SELECT m.* FROM messages m
      INNER JOIN channels c ON m.channel = c.name
      INNER JOIN channel_members cm ON c.id = cm.channel_id AND cm.agent_id = ?
      LEFT JOIN read_receipts rr ON m.id = rr.message_id AND rr.agent_id = ?
      WHERE m.sender != ?
        AND rr.message_id IS NULL
      ORDER BY m.seq ASC
    `;
    const rows = this.db.prepare(sql).all(agentId, agentId, agentId) as any[];
    return rows.map(rowToMessage);
  }

  async markRead(agentId: string, messageIds: string[]): Promise<void> {
    const stmt = this.db.prepare(
      'INSERT OR IGNORE INTO read_receipts (agent_id, message_id) VALUES (?, ?)',
    );
    const txn = this.db.transaction((ids: string[]) => {
      for (const msgId of ids) {
        stmt.run(agentId, msgId);
      }
    });
    txn(messageIds);
  }

  /**
   * Add a member to an existing channel. Used by ChannelManager during sync.
   */
  async addMember(channelName: string, agentId: string): Promise<void> {
    const ch = this.db.prepare('SELECT id FROM channels WHERE name = ?').get(channelName) as any;
    if (!ch) throw new Error(`Channel not found: ${channelName}`);
    this.db.prepare(
      'INSERT OR IGNORE INTO channel_members (channel_id, agent_id) VALUES (?, ?)',
    ).run(ch.id, agentId);
  }

  /**
   * Create a channel with the autoGenerated flag set. Used by ChannelManager.
   */
  async createAutoChannel(name: string, members: string[]): Promise<Channel> {
    const existing = this.db.prepare('SELECT id FROM channels WHERE name = ?').get(name);
    if (existing) {
      // Already exists — just ensure members are synced
      for (const agentId of members) {
        await this.addMember(name, agentId);
      }
      const ch = existing as any;
      const memberRows = this.db.prepare(
        'SELECT agent_id FROM channel_members WHERE channel_id = ?',
      ).all(ch.id) as any[];
      return {
        id: ch.id,
        name,
        members: memberRows.map((m: any) => m.agent_id),
        createdAt: new Date(),
        autoGenerated: true,
      };
    }

    const id = randomUUID();
    this.db.prepare(
      'INSERT INTO channels (id, name, auto_generated) VALUES (?, ?, 1)',
    ).run(id, name);

    const insertMember = this.db.prepare(
      'INSERT INTO channel_members (channel_id, agent_id) VALUES (?, ?)',
    );
    for (const agentId of members) {
      insertMember.run(id, agentId);
    }

    return {
      id,
      name,
      members,
      createdAt: new Date(),
      autoGenerated: true,
    };
  }

  close(): void {
    this.db.close();
  }
}
