export interface Message {
  id: string;
  channel: string;
  sender: string;
  content: string;
  thread?: string;           // Parent message ID for threaded replies
  mentions?: string[];       // Agent IDs extracted from @agent-id patterns in content
  timestamp: Date;
  metadata?: Record<string, unknown>;
}

export interface Channel {
  id: string;
  name: string;
  members: string[];
  createdAt: Date;
  autoGenerated: boolean;    // true = derived from org tree
}

export interface ICommsProvider {
  postMessage(
    channel: string,
    sender: string,
    content: string,
    opts?: { thread?: string },
  ): Promise<Message>;

  readChannel(
    channel: string,
    opts?: { limit?: number; since?: Date },
  ): Promise<Message[]>;

  searchHistory(
    query: string,
    opts?: { channel?: string; sender?: string },
  ): Promise<Message[]>;

  listChannels(): Promise<Channel[]>;

  createChannel(
    name: string,
    members?: string[],
  ): Promise<Channel>;

  getUnread(agentId: string): Promise<Message[]>;

  markRead(agentId: string, messageIds: string[]): Promise<void>;

  createAutoChannel(
    name: string,
    members: string[],
  ): Promise<Channel>;

  addMember(channelName: string, agentId: string): Promise<void>;
}
